//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste_ETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class mjesto
    {
        public mjesto()
        {
            this.artikli = new HashSet<artikli>();
        }
    
        public int id_mjesta { get; set; }
        public Nullable<int> polica { get; set; }
        public string sektor { get; set; }
        public Nullable<float> kolicina { get; set; }
    
        public virtual ICollection<artikli> artikli { get; set; }
    }
}
