//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste_ETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class poslovni_partner
    {
        public poslovni_partner()
        {
            this.dokument = new HashSet<dokument>();
        }
    
        public int id_partnera { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string br_telefona { get; set; }
    
        public virtual ICollection<dokument> dokument { get; set; }
    }
}
