//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste_ETI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class T02_DBEntities : DbContext
    {
        public T02_DBEntities()
            : base("name=T02_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<artikli> artikli { get; set; }
        public DbSet<dokument> dokument { get; set; }
        public DbSet<korisnik> korisnik { get; set; }
        public DbSet<mjesto> mjesto { get; set; }
        public DbSet<poslovni_partner> poslovni_partner { get; set; }
        public DbSet<stavke> stavke { get; set; }
        public DbSet<tip_dokumenta> tip_dokumenta { get; set; }
        public DbSet<tip_korisnika> tip_korisnika { get; set; }
    
        public virtual int UpdateArtikliDoprema(Nullable<int> iDArtikla, Nullable<double> dopremljenaKolicina, Nullable<double> dopremljenaMasa)
        {
            var iDArtiklaParameter = iDArtikla.HasValue ?
                new ObjectParameter("IDArtikla", iDArtikla) :
                new ObjectParameter("IDArtikla", typeof(int));
    
            var dopremljenaKolicinaParameter = dopremljenaKolicina.HasValue ?
                new ObjectParameter("DopremljenaKolicina", dopremljenaKolicina) :
                new ObjectParameter("DopremljenaKolicina", typeof(double));
    
            var dopremljenaMasaParameter = dopremljenaMasa.HasValue ?
                new ObjectParameter("DopremljenaMasa", dopremljenaMasa) :
                new ObjectParameter("DopremljenaMasa", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateArtikliDoprema", iDArtiklaParameter, dopremljenaKolicinaParameter, dopremljenaMasaParameter);
        }
    
        public virtual int UpdateArtikliOtprema(Nullable<int> iDArtikla, Nullable<double> otpremljenaKolicina, Nullable<double> otpremljenaMasa)
        {
            var iDArtiklaParameter = iDArtikla.HasValue ?
                new ObjectParameter("IDArtikla", iDArtikla) :
                new ObjectParameter("IDArtikla", typeof(int));
    
            var otpremljenaKolicinaParameter = otpremljenaKolicina.HasValue ?
                new ObjectParameter("OtpremljenaKolicina", otpremljenaKolicina) :
                new ObjectParameter("OtpremljenaKolicina", typeof(double));
    
            var otpremljenaMasaParameter = otpremljenaMasa.HasValue ?
                new ObjectParameter("OtpremljenaMasa", otpremljenaMasa) :
                new ObjectParameter("OtpremljenaMasa", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateArtikliOtprema", iDArtiklaParameter, otpremljenaKolicinaParameter, otpremljenaMasaParameter);
        }
    
        public virtual int UpdateArtikliStavkeMinus(Nullable<int> iDArtikla, Nullable<double> novaKolicina, Nullable<double> novaMasa)
        {
            var iDArtiklaParameter = iDArtikla.HasValue ?
                new ObjectParameter("IDArtikla", iDArtikla) :
                new ObjectParameter("IDArtikla", typeof(int));
    
            var novaKolicinaParameter = novaKolicina.HasValue ?
                new ObjectParameter("NovaKolicina", novaKolicina) :
                new ObjectParameter("NovaKolicina", typeof(double));
    
            var novaMasaParameter = novaMasa.HasValue ?
                new ObjectParameter("NovaMasa", novaMasa) :
                new ObjectParameter("NovaMasa", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateArtikliStavkeMinus", iDArtiklaParameter, novaKolicinaParameter, novaMasaParameter);
        }
    
        public virtual int UpdateArtikliStavkePlus(Nullable<int> iDArtikla, Nullable<double> novaKolicina, Nullable<double> novaMasa)
        {
            var iDArtiklaParameter = iDArtikla.HasValue ?
                new ObjectParameter("IDArtikla", iDArtikla) :
                new ObjectParameter("IDArtikla", typeof(int));
    
            var novaKolicinaParameter = novaKolicina.HasValue ?
                new ObjectParameter("NovaKolicina", novaKolicina) :
                new ObjectParameter("NovaKolicina", typeof(double));
    
            var novaMasaParameter = novaMasa.HasValue ?
                new ObjectParameter("NovaMasa", novaMasa) :
                new ObjectParameter("NovaMasa", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateArtikliStavkePlus", iDArtiklaParameter, novaKolicinaParameter, novaMasaParameter);
        }
    
        public virtual int UpdateDokumentStanje(Nullable<int> iDDokumenta)
        {
            var iDDokumentaParameter = iDDokumenta.HasValue ?
                new ObjectParameter("IDDokumenta", iDDokumenta) :
                new ObjectParameter("IDDokumenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDokumentStanje", iDDokumentaParameter);
        }
    }
}
