//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste_ETI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class T02_DBEntities : DbContext
    {
        public T02_DBEntities()
            : base("name=T02_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<artikli> artikli { get; set; }
        public DbSet<dokument> dokument { get; set; }
        public DbSet<korisnik> korisnik { get; set; }
        public DbSet<mjesto> mjesto { get; set; }
        public DbSet<poslovni_partner> poslovni_partner { get; set; }
        public DbSet<stavke> stavke { get; set; }
        public DbSet<tip_dokumenta> tip_dokumenta { get; set; }
        public DbSet<tip_korisnika> tip_korisnika { get; set; }
    
        public virtual int UpdateArtikliDoprema(Nullable<int> iDArtikla, Nullable<double> dopremljenaKolicina, Nullable<double> dopremljenaMasa)
        {
            var iDArtiklaParameter = iDArtikla.HasValue ?
                new ObjectParameter("IDArtikla", iDArtikla) :
                new ObjectParameter("IDArtikla", typeof(int));
    
            var dopremljenaKolicinaParameter = dopremljenaKolicina.HasValue ?
                new ObjectParameter("DopremljenaKolicina", dopremljenaKolicina) :
                new ObjectParameter("DopremljenaKolicina", typeof(double));
    
            var dopremljenaMasaParameter = dopremljenaMasa.HasValue ?
                new ObjectParameter("DopremljenaMasa", dopremljenaMasa) :
                new ObjectParameter("DopremljenaMasa", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateArtikliDoprema", iDArtiklaParameter, dopremljenaKolicinaParameter, dopremljenaMasaParameter);
        }
    }
}
