//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste_ETI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T02_DBEntities1 : DbContext
    {
        public T02_DBEntities1()
            : base("name=T02_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<artikli> artikli { get; set; }
        public DbSet<dokument> dokument { get; set; }
        public DbSet<korisnik> korisnik { get; set; }
        public DbSet<mjesto> mjesto { get; set; }
        public DbSet<poslovni_partner> poslovni_partner { get; set; }
        public DbSet<stavke> stavke { get; set; }
        public DbSet<tip_dokumenta> tip_dokumenta { get; set; }
        public DbSet<tip_korisnika> tip_korisnika { get; set; }
    }
}
