//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste_ETI
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavke
    {
        public int id_stavke { get; set; }
        public Nullable<int> dokument_id_dokumenta { get; set; }
        public Nullable<int> artikli_id_artikla { get; set; }
        public int kolicina { get; set; }
        public int masa { get; set; }
    
        public virtual artikli artikli { get; set; }
        public virtual dokument dokument { get; set; }
    }
}
